name: Setup Website
description: Prepare Website in GitHub Actions

inputs:
  node-version:
    description: Version of Node to use
    default: 18.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash

    - name: 🛠 Build dependencies
      run: yarn turbo build --filter '{./website}^...'
      shell: bash

    # Webpack 4 uses legacy hashing algorithm that is not supported by Node 18+
    # This adds the workaround, AFTER Node is fully installed, avoiding "is not allowed" error
    # See: https://stackoverflow.com/questions/72866798/node-openssl-legacy-provider-is-not-allowed-in-node-options
    - name: 🐛 Add Webpack 4 workaround
      run: echo "NODE_OPTIONS=\"--openssl-legacy-provider\"" >> $GITHUB_ENV
      shell: bash
