name: Setup Website
description: Prepare Website in GitHub Actions

inputs:
  node-version:
    description: Version of Node to use
    default: 16.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash

    - name: 🛠 Build dependencies
      run: yarn turbo build --filter '{./website}^...'
      shell: bash
