name: Setup Snackager
description: Prepare Snackager in GitHub Actions

inputs:
  node-version:
    description: Version of Node to use
    default: 16.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    # Cache the build files when coupled within the monorepo
    - name: 🏗 Setup caching
      uses: actions/cache@v3
      if: ${{ !matrix.monorepo-detached }}
      with:
        key: turbo-snackager-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-snackager-${{ runner.os }}
          turbo-snackager
        path: |
          node_modules/.cache/turbo
          packages/*/.turbo

    # npm v7+ doesn't work well with our monorepo
    - name: 🐛 Downgrade npm to v6
      run: npm install --global npm@^6
      working-directory: ../
      shell: bash

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash

    - name: 🛠 Build packages
      run: yarn turbo build -- --filter "{./snackager}..."
      shell: bash
